-- AMAZON SALES DATA CLEANING & VALIDATION PIPELINE (Snowflake)
USE DATABASE IF NOT EXISTS AMAZON_SALES_DB;
CREATE DATABASE IF NOT EXISTS AMAZON_SALES_DB;
USE SCHEMA IF NOT EXISTS SALES_SCHEMA;
CREATE SCHEMA IF NOT EXISTS SALES_SCHEMA;
USE WAREHOUSE SALES_WH;

-- Create RAW table (if not exists)
CREATE OR REPLACE TABLE RAW_AMAZON_SALES (
  ORDER_ID STRING,
  DATE STRING,
  PRODUCT STRING,
  CATEGORY STRING,
  SUB_CATEGORY STRING,
  QUANTITY INT,
  UNIT_PRICE FLOAT,
  DISCOUNT FLOAT,
  PROFIT FLOAT,
  REGION STRING,
  COUNTRY STRING
);

-- Load step: uncomment and adjust if using a stage
-- COPY INTO RAW_AMAZON_SALES FROM @AMAZON_STAGE/amazon_sales_data.csv
-- FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

-- STEP 1: Deduplicate keeping latest by DATE
CREATE OR REPLACE TABLE STG_DEDUPED_SALES AS
SELECT *
FROM (
  SELECT *,
         ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY DATE DESC NULLS LAST) AS rn
  FROM RAW_AMAZON_SALES
)
QUALIFY rn = 1;

-- STEP 2: Clean and standardize
CREATE OR REPLACE TABLE STG_CLEAN_SALES AS
SELECT
  ORDER_ID,
  TRY_TO_DATE(DATE, 'YYYY-MM-DD') AS ORDER_DATE,
  INITCAP(TRIM(COALESCE(PRODUCT, 'Unknown Product'))) AS PRODUCT,
  INITCAP(TRIM(COALESCE(CATEGORY, 'Miscellaneous'))) AS CATEGORY,
  INITCAP(TRIM(COALESCE(SUB_CATEGORY, 'N/A'))) AS SUB_CATEGORY,
  COALESCE(QUANTITY, 0) AS QUANTITY,
  COALESCE(UNIT_PRICE, 0) AS UNIT_PRICE,
  COALESCE(DISCOUNT, 0) AS DISCOUNT,
  COALESCE(PROFIT, 0) AS PROFIT,
  INITCAP(TRIM(COALESCE(REGION, 'Unknown'))) AS REGION,
  INITCAP(TRIM(COALESCE(COUNTRY, 'Unknown'))) AS COUNTRY
FROM STG_DEDUPED_SALES
WHERE ORDER_ID IS NOT NULL
  AND QUANTITY >= 0
  AND UNIT_PRICE >= 0;

-- STEP 3: Enrich with derived columns
CREATE OR REPLACE TABLE FINAL_AMAZON_SALES AS
SELECT
  ORDER_ID,
  ORDER_DATE,
  PRODUCT,
  CATEGORY,
  SUB_CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  DISCOUNT,
  PROFIT,
  REGION,
  COUNTRY,
  (QUANTITY * UNIT_PRICE) AS TOTAL_SALES,
  (QUANTITY * UNIT_PRICE) - DISCOUNT AS NET_SALES,
  ROUND(CASE WHEN (QUANTITY * UNIT_PRICE) = 0 THEN 0 ELSE (PROFIT / NULLIF((QUANTITY * UNIT_PRICE),0) * 100) END,2) AS PROFIT_MARGIN
FROM STG_CLEAN_SALES;

-- STEP 4: Aggregations for reporting
CREATE OR REPLACE TABLE AGG_SALES_SUMMARY AS
SELECT
  CATEGORY,
  REGION,
  DATE_TRUNC('month', ORDER_DATE) AS MONTH,
  SUM(QUANTITY) AS TOTAL_QUANTITY,
  SUM(TOTAL_SALES) AS TOTAL_SALES,
  SUM(NET_SALES) AS TOTAL_NET_SALES,
  SUM(PROFIT) AS TOTAL_PROFIT
FROM FINAL_AMAZON_SALES
GROUP BY CATEGORY, REGION, DATE_TRUNC('month', ORDER_DATE);

-- STEP 5: Validation report
CREATE OR REPLACE TABLE VALIDATION_REPORT AS
SELECT
  (SELECT COUNT(*) FROM RAW_AMAZON_SALES) AS raw_count,
  (SELECT COUNT(*) FROM FINAL_AMAZON_SALES) AS final_count,
  (SELECT COUNT(DISTINCT ORDER_ID) FROM FINAL_AMAZON_SALES) AS unique_orders,
  (SELECT COUNT(*) FROM FINAL_AMAZON_SALES WHERE ORDER_DATE IS NULL) AS null_dates,
  (SELECT COUNT(*) FROM FINAL_AMAZON_SALES WHERE TOTAL_SALES < 0) AS invalid_sales;

-- View validation summary
SELECT * FROM VALIDATION_REPORT;
